/**
 * Writes the one stylesheet that ties Tailwind to the active storefront set.
 *
 * Two things have to agree with the import alias, and both are invisible when
 * they do not: which set's tokens are loaded, and which directory Tailwind
 * scans for utilities. Point either at the wrong set and the build still
 * succeeds — it just ships the wrong palette, or no utilities at all. So both
 * are generated from the same resolved id rather than written by hand.
 *
 * The file is generated, not committed: it names whichever set this checkout
 * has selected.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { SETS_DIR, discoverSetIds } from './storefront-set.mjs';

export const ACTIVE_CSS = 'src/styles/storefront-active.css';
export const ACTIVE_TSCONFIG = 'tsconfig.storefront.json';

export function activeStorefrontCss(id, root = process.cwd()) {
  const dir = SETS_DIR.replace('src/', '');
  // Exclude each INACTIVE set individually. Excluding the parent and then
  // re-including the active child does not work: the exclusion wins, and the
  // active set's utilities silently vanish along with the others'. Verified by
  // building a probe set and finding its unique utility absent even when the
  // probe was selected.
  const inactive = discoverSetIds(root).filter((other) => other !== id);
  const exclusions = inactive.length
    ? inactive.map((other) => `@source not "../${dir}/${other}";`).join('\n')
    : '/* no inactive sets */';

  return `/*
 * GENERATED — do not edit, and do not commit.
 * Written by scripts/storefront-css.mjs from the resolved storefront set.
 * Active set: ${id}
 */

/* Tailwind auto-detects sources, so every sibling set would otherwise
   contribute utilities no page can use. Inactive sets are excluded one by one;
   the active set is left to normal detection. */
${exclusions}

/* The active set's design tokens. src/styles/theme.css is imported after this
   by global.css, so a merchant's overrides still win. */
@import "../${dir}/${id}/theme.css";
`;
}

/** Idempotent: only rewrites when the content changes, so a dev server does not
 *  see a modification on every config load. */
export function writeActiveStorefrontCss(id, root = process.cwd()) {
  const file = resolve(root, ACTIVE_CSS);
  const next = activeStorefrontCss(id, root);
  try {
    if (readFileSync(file, 'utf8') === next) return file;
  } catch {
    // Not written yet.
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, next);
  return file;
}

/**
 * TypeScript cannot follow a Vite alias, so `astro check` needs the same
 * mapping as a `paths` entry. Generated from the resolved id for the same
 * reason as the CSS: a hardcoded path would type-check one set while the build
 * compiled another.
 */
export function writeActiveStorefrontTsconfig(id, root = process.cwd()) {
  const file = resolve(root, ACTIVE_TSCONFIG);
  const next = `${JSON.stringify(
    {
      $comment: `GENERATED by scripts/storefront-css.mjs — active set: ${id}. Do not edit or commit.`,
      compilerOptions: { paths: { '#storefront/*': [`./${SETS_DIR}/${id}/*`] } },
    },
    null,
    2,
  )}\n`;
  try {
    if (readFileSync(file, 'utf8') === next) return file;
  } catch {
    // Not written yet.
  }
  writeFileSync(file, next);
  return file;
}
