/**
 * Generates the artifacts that tie Tailwind and TypeScript to storefront sets.
 *
 * Two things have to agree with the `#storefront` import alias, and both are
 * invisible when they do not: which set's tokens are loaded, and which
 * directory Tailwind scans for utilities. Point either at the wrong set and
 * the build still succeeds — it just ships the wrong palette, or no utilities
 * at all.
 *
 * DESIGN RULE: every write here is a deterministic function of the set list on
 * disk plus storefront.config.json. The STOREFRONT environment variable never
 * changes a single generated byte. This is what makes concurrent processes
 * safe: a `STOREFRONT=studio astro build` running beside a default dev server
 * writes exactly the bytes the dev server would write, the idempotent-write
 * skip turns that into no write at all, and no watcher fires. (Before this
 * rule, that exact scenario shipped a corrupt worker: the dev server noticed
 * the shared tsconfig change, restarted, wrote both shared files back to its
 * own set, and the build's Tailwind then read the reverted stylesheet — it
 * exited 0 carrying studio templates with default styling.)
 *
 * Per-process selection happens in process-local state only:
 *   - the `#storefront` and `#storefront-css` Vite aliases (astro.config.mjs,
 *     vitest.config.ts)
 *   - an explicit `astro check --tsconfig tsconfig.storefront.<id>.json`
 *
 * The files are generated, not committed.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { CONFIG_FILE, SETS_DIR, discoverSetIds, resolveConfiguredSet } from './storefront-set.mjs';

/** One stylesheet per set, so selecting a set is an alias, not a rewrite. */
export const GENERATED_CSS_DIR = 'src/styles/storefront';
/** The editor-facing tsconfig fragment; follows storefront.config.json only. */
export const SHARED_TSCONFIG = 'tsconfig.storefront.json';

export function setCssPath(id, root = process.cwd()) {
  return resolve(root, GENERATED_CSS_DIR, `${id}.css`);
}

export function setTsconfigPath(id, root = process.cwd()) {
  return resolve(root, `tsconfig.storefront.${id}.json`);
}

export function storefrontSetCss(id, root = process.cwd()) {
  // Relative to GENERATED_CSS_DIR (src/styles/storefront/).
  const toSets = '../../storefront';
  // Exclude each INACTIVE set individually. Excluding the parent and then
  // re-including the active child does not work: the exclusion wins, and the
  // active set's utilities silently vanish along with the others'. Verified by
  // building a probe set and finding its unique utility absent even when the
  // probe was selected.
  const inactive = discoverSetIds(root).filter((other) => other !== id);
  const exclusions = inactive.length
    ? inactive.map((other) => `@source not "${toSets}/${other}";`).join('\n')
    : '/* no inactive sets */';

  return `/*
 * GENERATED — do not edit, and do not commit.
 * Written by scripts/storefront-css.mjs. One of these exists per set; the
 * #storefront-css alias picks which one a given process compiles.
 * This file selects: ${id}
 */

/* Tailwind auto-detects sources, so every sibling set would otherwise
   contribute utilities no page can use. Inactive sets are excluded one by one;
   the active set is left to normal detection. */
${exclusions}

/* The active set's design tokens. src/styles/theme.css is imported after this
   by global.css, so a merchant's overrides still win. */
@import "${toSets}/${id}/theme.css";
`;
}

function storefrontSetTsconfig(id) {
  return `${JSON.stringify(
    {
      $comment: `GENERATED by scripts/storefront-css.mjs — selects set: ${id}. Do not edit or commit. Consumed via astro check --tsconfig.`,
      extends: './tsconfig.json',
      compilerOptions: { paths: { '#storefront/*': [`./${SETS_DIR}/${id}/*`] } },
    },
    null,
    2,
  )}\n`;
}

function sharedTsconfig(id) {
  return `${JSON.stringify(
    {
      $comment: `GENERATED by scripts/storefront-css.mjs from ${CONFIG_FILE} — set: ${id}. Do not edit or commit.`,
      compilerOptions: { paths: { '#storefront/*': [`./${SETS_DIR}/${id}/*`] } },
    },
    null,
    2,
  )}\n`;
}

/** Idempotent: only rewrites when the content changes, so a watching dev
 *  server never sees a modification event for identical bytes. */
function writeIfChanged(file, next) {
  try {
    if (readFileSync(file, 'utf8') === next) return file;
  } catch {
    // Not written yet.
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, next);
  return file;
}

/**
 * Write everything: one CSS file and one tsconfig per discovered set, plus the
 * shared editor tsconfig from the config file. Artifacts for sets that no
 * longer exist are removed, so a deleted set does not leave a pair pointing at
 * a missing directory. Called by astro.config.mjs (so a bare `astro dev` on a
 * fresh clone works) and by `npm run storefront:sync`.
 */
export function writeStorefrontArtifacts(root = process.cwd()) {
  const ids = discoverSetIds(root);
  for (const id of ids) {
    writeIfChanged(setCssPath(id, root), storefrontSetCss(id, root));
    writeIfChanged(setTsconfigPath(id, root), storefrontSetTsconfig(id));
  }

  const live = new Set(ids);
  const cssDir = resolve(root, GENERATED_CSS_DIR);
  if (existsSync(cssDir)) {
    for (const name of readdirSync(cssDir)) {
      const id = name.replace(/\.css$/, '');
      if (name.endsWith('.css') && !live.has(id)) rmSync(resolve(cssDir, name), { force: true });
    }
  }
  for (const name of readdirSync(root)) {
    const m = name.match(/^tsconfig\.storefront\.([a-z0-9-]+)\.json$/);
    if (m && !live.has(m[1])) rmSync(resolve(root, name), { force: true });
  }

  // The one shared file. It exists for the editor and for a bare `astro
  // check`, and it deliberately ignores STOREFRONT — see the design rule
  // above. Env-selected processes pass their per-set tsconfig explicitly.
  const configured = resolveConfiguredSet(root);
  writeIfChanged(resolve(root, SHARED_TSCONFIG), sharedTsconfig(configured.id));

  // The pre-per-set generated stylesheet. Nothing imports it any more; leaving
  // a stale generated file behind invites something to.
  rmSync(resolve(root, 'src/styles/storefront-active.css'), { force: true });

  return { ids, configured };
}
